package pckg;

typedef enum logic [10:0] {

  /* =========================================================
   * TX INIT / RX INIT – D2C TRAINING (NO DATA)
   * ========================================================= */
  SB_START_TXINIT_D2C_POINT_TEST_RESP,
  SB_LFSR_CLEAR_ERROR_REQ,
  SB_LFSR_CLEAR_ERROR_RESP,
  SB_TXINIT_D2C_RESULTS_REQ,
  SB_END_TXINIT_D2C_POINT_TEST_REQ,
  SB_END_TXINIT_D2C_POINT_TEST_RESP,
  SB_START_TXINIT_D2C_EYE_SWEEP_RESP,
  SB_END_TXINIT_D2C_EYE_SWEEP_REQ,
  SB_END_TXINIT_D2C_EYE_SWEEP_RESP,

  SB_START_RXINIT_D2C_POINT_TEST_RESP,
  SB_RXINIT_D2C_TX_COUNT_DONE_REQ,
  SB_RXINIT_D2C_TX_COUNT_DONE_RESP,
  SB_END_RXINIT_D2C_POINT_TEST_REQ,
  SB_END_RXINIT_D2C_POINT_TEST_RESP,
  SB_START_RXINIT_D2C_EYE_SWEEP_RESP,
  SB_RXINIT_D2C_RESULTS_REQ,
  SB_END_RXINIT_D2C_EYE_SWEEP_REQ,
  SB_END_RXINIT_D2C_EYE_SWEEP_RESP,

  /* =========================================================
   * TX INIT / RX INIT – D2C TRAINING (WITH DATA)
   * ========================================================= */
  SB_TXINIT_D2C_POINT_TEST_START_REQ,
  SB_TXINIT_D2C_RESULTS_RESP,
  SB_TXINIT_D2C_EYE_SWEEP_START_REQ,

  SB_RXINIT_D2C_POINT_TEST_START_REQ,
  SB_RXINIT_D2C_EYE_SWEEP_START_REQ,
  SB_RXINIT_D2C_RESULTS_RESP,
  SB_RXINIT_D2C_SWEEP_DONE_WITH_RESULTS,

  /* =========================================================
   * SBINIT
   * ========================================================= */
  SB_SBINIT_OUT_OF_RESET,
  SB_SBINIT_DONE_REQ,
  SB_SBINIT_DONE_RESP,

  /* =========================================================
   * MBINIT – CAL / PARAM / SBFE
   * ========================================================= */
  SB_MBINIT_CAL_DONE_REQ,
  SB_MBINIT_CAL_DONE_RESP,

  SB_MBINIT_PARAM_CONFIG_REQ,
  SB_MBINIT_PARAM_CONFIG_RESP,

  SB_MBINIT_PARAM_SBFE_REQ,
  SB_MBINIT_PARAM_SBFE_RESP,

  /* =========================================================
   * MBINIT – REPAIRCLK
   * ========================================================= */
  SB_MBINIT_REPAIRCLK_INIT_REQ,
  SB_MBINIT_REPAIRCLK_INIT_RESP,
  SB_MBINIT_REPAIRCLK_RESULT_REQ,
  SB_MBINIT_REPAIRCLK_RESULT_RESP,
  SB_MBINIT_REPAIRCLK_APPLY_REPAIR_REQ,
  SB_MBINIT_REPAIRCLK_APPLY_REPAIR_RESP,
  SB_MBINIT_REPAIRCLK_CHECK_INIT_REQ,
  SB_MBINIT_REPAIRCLK_CHECK_INIT_RESP,
  SB_MBINIT_REPAIRCLK_CHECK_RESULTS_REQ,
  SB_MBINIT_REPAIRCLK_CHECK_RESULTS_RESP,
  SB_MBINIT_REPAIRCLK_DONE_REQ,
  SB_MBINIT_REPAIRCLK_DONE_RESP,

  /* =========================================================
   * MBINIT – REPAIRVAL
   * ========================================================= */
  SB_MBINIT_REPAIRVAL_INIT_REQ,
  SB_MBINIT_REPAIRVAL_INIT_RESP,
  SB_MBINIT_REPAIRVAL_RESULT_REQ,
  SB_MBINIT_REPAIRVAL_RESULT_RESP,
  SB_MBINIT_REPAIRVAL_APPLY_REPAIR_REQ,
  SB_MBINIT_REPAIRVAL_APPLY_REPAIR_RESP,
  SB_MBINIT_REPAIRVAL_DONE_REQ,
  SB_MBINIT_REPAIRVAL_DONE_RESP,

  /* =========================================================
   * MBINIT – REVERSALMB
   * ========================================================= */
  SB_MBINIT_REVERSALMB_INIT_REQ,
  SB_MBINIT_REVERSALMB_INIT_RESP,
  SB_MBINIT_REVERSALMB_CLEAR_ERROR_REQ,
  SB_MBINIT_REVERSALMB_CLEAR_ERROR_RESP,
  SB_MBINIT_REVERSALMB_RESULT_REQ,
  SB_MBINIT_REVERSALMB_RESULT_RESP,
  SB_MBINIT_REVERSALMB_DONE_REQ,
  SB_MBINIT_REVERSALMB_DONE_RESP,

  /* =========================================================
   * MBINIT – REPAIRMB
   * ========================================================= */
  SB_MBINIT_REPAIRMB_START_REQ,
  SB_MBINIT_REPAIRMB_START_RESP,
  SB_MBINIT_REPAIRMB_APPLY_REPAIR_REQ,
  SB_MBINIT_REPAIRMB_APPLY_REPAIR_RESP,
  SB_MBINIT_REPAIRMB_END_REQ,
  SB_MBINIT_REPAIRMB_END_RESP,
  SB_MBINIT_REPAIRMB_APPLY_DEGRADE_REQ,
  SB_MBINIT_REPAIRMB_APPLY_DEGRADE_RESP,

  /* =========================================================
   * MBTRAIN – VREF / CENTER / SPEED / REPAIR
   * ========================================================= */
  SB_MBTRAIN_VALVREF_START_REQ,
  SB_MBTRAIN_VALVREF_START_RESP,
  SB_MBTRAIN_VALVREF_END_REQ,
  SB_MBTRAIN_VALVREF_END_RESP,

  SB_MBTRAIN_DATAVREF_START_REQ,
  SB_MBTRAIN_DATAVREF_START_RESP,
  SB_MBTRAIN_DATAVREF_END_REQ,
  SB_MBTRAIN_DATAVREF_END_RESP,

  SB_MBTRAIN_SPEEDIDLE_DONE_REQ,
  SB_MBTRAIN_SPEEDIDLE_DONE_RESP,

  SB_MBTRAIN_TXSELFCAL_DONE_REQ,
  SB_MBTRAIN_TXSELFCAL_DONE_RESP,

  SB_MBTRAIN_RXCLKCAL_START_REQ,
  SB_MBTRAIN_RXCLKCAL_START_RESP,
  SB_MBTRAIN_RXCLKCAL_DONE_REQ,
  SB_MBTRAIN_RXCLKCAL_DONE_RESP,

  SB_MBTRAIN_VALTRAINCENTER_START_REQ,
  SB_MBTRAIN_VALTRAINCENTER_START_RESP,
  SB_MBTRAIN_VALTRAINCENTER_DONE_REQ,
  SB_MBTRAIN_VALTRAINCENTER_DONE_RESP,

  SB_MBTRAIN_VALTRAINVREF_START_REQ,
  SB_MBTRAIN_VALTRAINVREF_START_RESP,
  SB_MBTRAIN_VALTRAINVREF_DONE_REQ,
  SB_MBTRAIN_VALTRAINVREF_DONE_RESP,

  SB_MBTRAIN_DATATRAINCENTER1_START_REQ,
  SB_MBTRAIN_DATATRAINCENTER1_START_RESP,
  SB_MBTRAIN_DATATRAINCENTER1_END_REQ,
  SB_MBTRAIN_DATATRAINCENTER1_END_RESP,

  SB_MBTRAIN_DATATRAINVREF_START_REQ,
  SB_MBTRAIN_DATATRAINVREF_START_RESP,
  SB_MBTRAIN_DATATRAINVREF_END_REQ,
  SB_MBTRAIN_DATATRAINVREF_END_RESP,

  SB_MBTRAIN_RXDESKEW_START_REQ,
  SB_MBTRAIN_RXDESKEW_START_RESP,
  SB_MBTRAIN_RXDESKEW_END_REQ,
  SB_MBTRAIN_RXDESKEW_END_RESP,

  SB_MBTRAIN_DATATRAINCENTER2_START_REQ,
  SB_MBTRAIN_DATATRAINCENTER2_START_RESP,
  SB_MBTRAIN_DATATRAINCENTER2_END_REQ,
  SB_MBTRAIN_DATATRAINCENTER2_END_RESP,

  SB_MBTRAIN_LINKSPEED_START_REQ,
  SB_MBTRAIN_LINKSPEED_START_RESP,
  SB_MBTRAIN_LINKSPEED_ERROR_REQ,
  SB_MBTRAIN_LINKSPEED_ERROR_RESP,
  SB_MBTRAIN_LINKSPEED_EXIT_REPAIR_REQ,
  SB_MBTRAIN_LINKSPEED_EXIT_REPAIR_RESP,
  SB_MBTRAIN_LINKSPEED_EXIT_DEGRADE_REQ,
  SB_MBTRAIN_LINKSPEED_EXIT_DEGRADE_RESP,
  SB_MBTRAIN_LINKSPEED_DONE_REQ,
  SB_MBTRAIN_LINKSPEED_DONE_RESP,
  //SB_MBTRAIN_LINKSPEED_MULTI_MODULE_DISABLE_RESP,
  SB_MBTRAIN_LINKSPEED_EXIT_PHYRETRAIN_REQ,
  SB_MBTRAIN_LINKSPEED_EXIT_PHYRETRAIN_RESP,

  SB_MBTRAIN_REPAIR_INIT_REQ,
  SB_MBTRAIN_REPAIR_INIT_RESP,
  SB_MBTRAIN_REPAIR_APPLY_REPAIR_REQ,
  SB_MBTRAIN_REPAIR_APPLY_REPAIR_RESP,
  SB_MBTRAIN_REPAIR_END_REQ,
  SB_MBTRAIN_REPAIR_END_RESP,
  SB_MBTRAIN_REPAIR_APPLY_DEGRADE_REQ,
  SB_MBTRAIN_REPAIR_APPLY_DEGRADE_RESP,

  SB_MBTRAIN_RXDESKEW_EQ_PRESET_REQ,
  SB_MBTRAIN_RXDESKEW_EQ_PRESET_RESP,
  SB_MBTRAIN_RXDESKEW_EXIT_DTC1_REQ,
  SB_MBTRAIN_RXDESKEW_EXIT_DTC1_RESP,

  /* =========================================================
   * MBTRAIN / PHY / RECAL (WITH DATA)
   * ========================================================= */
  SB_MBTRAIN_RXCLKCAL_TCKN_SHIFT_REQ,
  SB_MBTRAIN_RXCLKCAL_TCKN_SHIFT_RESP,

  SB_PHYRETRAIN_START_REQ,
  SB_PHYRETRAIN_START_RESP,

  SB_TRAINERROR_ENTRY_REQ,
  SB_TRAINERROR_ENTRY_RESP,

  SB_RECAL_TRACK_PATTERN_INIT_REQ,
  SB_RECAL_TRACK_PATTERN_INIT_RESP,
  SB_RECAL_TRACK_PATTERN_DONE_REQ,
  SB_RECAL_TRACK_PATTERN_DONE_RESP,
  SB_RECAL_TRACK_TX_ADJUST_REQ,
  SB_RECAL_TRACK_TX_ADJUST_RESP,

  /* =========================================================
   * LINK MGMT – RDI REQUEST
   * ========================================================= */
  SB_RDI_REQ_ACTIVE,
  SB_RDI_REQ_L1,
  SB_RDI_REQ_L2,
  SB_RDI_REQ_LINKRESET,
  SB_RDI_REQ_LINKERROR,
  SB_RDI_REQ_RETRAIN,
  SB_RDI_REQ_DISABLE,

  /* =========================================================
   * LINK MGMT – RDI RESPONSE
   * ========================================================= */
  SB_RDI_RSP_ACTIVE,
  SB_RDI_RSP_PMNAK,
  SB_RDI_RSP_L1,
  SB_RDI_RSP_L2,
  SB_RDI_RSP_LINKRESET,
  SB_RDI_RSP_LINKERROR,
  SB_RDI_RSP_RETRAIN,
  SB_RDI_RSP_DISABLE

} sb_msg_id;

typedef struct packed {
  logic [4:0]  opcode;
  logic [7:0]  msgcode;
  logic [7:0]  msgsubcode;
  logic        has_data;
} sb_pckt;

localparam logic [4:0]
  SB_OPCODE_NO_DATA = 5'b10010,
  SB_OPCODE_DATA    = 5'b11011;

const sb_pckt SB_MSG_LUT [sb_msg_id] = '{
    /* =========================================================
     * TX INIT / RX INIT – D2C TRAINING (NO DATA)
     * ========================================================= */
    SB_START_TXINIT_D2C_POINT_TEST_RESP: '{SB_OPCODE_NO_DATA, 8'h8A, 8'h01, 1'b0},
    SB_LFSR_CLEAR_ERROR_REQ:             '{SB_OPCODE_NO_DATA, 8'h85, 8'h02, 1'b0},
    SB_LFSR_CLEAR_ERROR_RESP:            '{SB_OPCODE_NO_DATA, 8'h8A, 8'h02, 1'b0},
    SB_TXINIT_D2C_RESULTS_REQ:           '{SB_OPCODE_NO_DATA, 8'h85, 8'h03, 1'b0},
    SB_END_TXINIT_D2C_POINT_TEST_REQ:    '{SB_OPCODE_NO_DATA, 8'h85, 8'h04, 1'b0},
    SB_END_TXINIT_D2C_POINT_TEST_RESP:   '{SB_OPCODE_NO_DATA, 8'h8A, 8'h04, 1'b0},
    SB_START_TXINIT_D2C_EYE_SWEEP_RESP:  '{SB_OPCODE_NO_DATA, 8'h8A, 8'h05, 1'b0},
    SB_END_TXINIT_D2C_EYE_SWEEP_REQ:     '{SB_OPCODE_NO_DATA, 8'h85, 8'h06, 1'b0},
    SB_END_TXINIT_D2C_EYE_SWEEP_RESP:    '{SB_OPCODE_NO_DATA, 8'h8A, 8'h06, 1'b0},

    SB_START_RXINIT_D2C_POINT_TEST_RESP: '{SB_OPCODE_NO_DATA, 8'h8A, 8'h07, 1'b0},
    SB_RXINIT_D2C_TX_COUNT_DONE_REQ:     '{SB_OPCODE_NO_DATA, 8'h85, 8'h08, 1'b0},
    SB_RXINIT_D2C_TX_COUNT_DONE_RESP:    '{SB_OPCODE_NO_DATA, 8'h8A, 8'h08, 1'b0},
    SB_END_RXINIT_D2C_POINT_TEST_REQ:    '{SB_OPCODE_NO_DATA, 8'h85, 8'h09, 1'b0},
    SB_END_RXINIT_D2C_POINT_TEST_RESP:   '{SB_OPCODE_NO_DATA, 8'h8A, 8'h09, 1'b0},
    SB_START_RXINIT_D2C_EYE_SWEEP_RESP:  '{SB_OPCODE_NO_DATA, 8'h8A, 8'h0A, 1'b0},
    SB_RXINIT_D2C_RESULTS_REQ:           '{SB_OPCODE_NO_DATA, 8'h85, 8'h0B, 1'b0},
    SB_END_RXINIT_D2C_EYE_SWEEP_REQ:     '{SB_OPCODE_NO_DATA, 8'h85, 8'h0C, 1'b0},
    SB_END_RXINIT_D2C_EYE_SWEEP_RESP:    '{SB_OPCODE_NO_DATA, 8'h8A, 8'h0C, 1'b0},

    /* =========================================================
     * TX INIT / RX INIT – D2C TRAINING (WITH DATA)
     * ========================================================= */
    SB_TXINIT_D2C_POINT_TEST_START_REQ:  '{SB_OPCODE_DATA, 8'h85, 8'h0D, 1'b1},
    SB_TXINIT_D2C_RESULTS_RESP:          '{SB_OPCODE_DATA, 8'h8A, 8'h0E, 1'b1},
    SB_TXINIT_D2C_EYE_SWEEP_START_REQ:   '{SB_OPCODE_DATA, 8'h85, 8'h0F, 1'b1},

    SB_RXINIT_D2C_POINT_TEST_START_REQ:  '{SB_OPCODE_DATA, 8'h85, 8'h10, 1'b1},
    SB_RXINIT_D2C_EYE_SWEEP_START_REQ:   '{SB_OPCODE_DATA, 8'h85, 8'h11, 1'b1},
    SB_RXINIT_D2C_RESULTS_RESP:          '{SB_OPCODE_DATA, 8'h8A, 8'h12, 1'b1},
    SB_RXINIT_D2C_SWEEP_DONE_WITH_RESULTS: '{SB_OPCODE_DATA, 8'h8A, 8'h13, 1'b1},

    /* =========================================================
     * SBINIT
     * ========================================================= */
    SB_SBINIT_OUT_OF_RESET:              '{SB_OPCODE_NO_DATA, 8'h95, 8'h00, 1'b0},
    SB_SBINIT_DONE_REQ:                  '{SB_OPCODE_NO_DATA, 8'h95, 8'h01, 1'b0},
    SB_SBINIT_DONE_RESP:                 '{SB_OPCODE_NO_DATA, 8'h9A, 8'h01, 1'b0},

    /* =========================================================
     * MBINIT – CAL / PARAM / SBFE
     * ========================================================= */
    SB_MBINIT_CAL_DONE_REQ:              '{SB_OPCODE_NO_DATA, 8'hA5, 8'h00, 1'b0},
    SB_MBINIT_CAL_DONE_RESP:             '{SB_OPCODE_NO_DATA, 8'hAA, 8'h00, 1'b0},

    SB_MBINIT_PARAM_CONFIG_REQ:          '{SB_OPCODE_NO_DATA, 8'hA5, 8'h01, 1'b0},
    SB_MBINIT_PARAM_CONFIG_RESP:         '{SB_OPCODE_NO_DATA, 8'hAA, 8'h01, 1'b0},

    SB_MBINIT_PARAM_SBFE_REQ:            '{SB_OPCODE_NO_DATA, 8'hA5, 8'h02, 1'b0},
    SB_MBINIT_PARAM_SBFE_RESP:           '{SB_OPCODE_NO_DATA, 8'hAA, 8'h02, 1'b0},

    /* =========================================================
     * MBINIT – REPAIRCLK
     * ========================================================= */
    SB_MBINIT_REPAIRCLK_INIT_REQ:        '{SB_OPCODE_NO_DATA, 8'hA5, 8'h03, 1'b0},
    SB_MBINIT_REPAIRCLK_INIT_RESP:       '{SB_OPCODE_NO_DATA, 8'hAA, 8'h03, 1'b0},
    SB_MBINIT_REPAIRCLK_RESULT_REQ:      '{SB_OPCODE_NO_DATA, 8'hA5, 8'h04, 1'b0},
    SB_MBINIT_REPAIRCLK_RESULT_RESP:     '{SB_OPCODE_NO_DATA, 8'hAA, 8'h04, 1'b0},
    SB_MBINIT_REPAIRCLK_APPLY_REPAIR_REQ: '{SB_OPCODE_DATA, 8'hA5, 8'h05, 1'b1},
    SB_MBINIT_REPAIRCLK_APPLY_REPAIR_RESP: '{SB_OPCODE_NO_DATA, 8'hAA, 8'h05, 1'b0},
    SB_MBINIT_REPAIRCLK_CHECK_INIT_REQ:  '{SB_OPCODE_NO_DATA, 8'hA5, 8'h06, 1'b0},
    SB_MBINIT_REPAIRCLK_CHECK_INIT_RESP: '{SB_OPCODE_NO_DATA, 8'hAA, 8'h06, 1'b0},
    SB_MBINIT_REPAIRCLK_CHECK_RESULTS_REQ: '{SB_OPCODE_NO_DATA, 8'hA5, 8'h07, 1'b0},
    SB_MBINIT_REPAIRCLK_CHECK_RESULTS_RESP: '{SB_OPCODE_NO_DATA, 8'hAA, 8'h07, 1'b0},
    SB_MBINIT_REPAIRCLK_DONE_REQ:        '{SB_OPCODE_NO_DATA, 8'hA5, 8'h08, 1'b0},
    SB_MBINIT_REPAIRCLK_DONE_RESP:       '{SB_OPCODE_NO_DATA, 8'hAA, 8'h08, 1'b0},

    /* =========================================================
     * MBINIT – REPAIRVAL
     * ========================================================= */
    SB_MBINIT_REPAIRVAL_INIT_REQ:        '{SB_OPCODE_NO_DATA, 8'hA5, 8'h09, 1'b0},
    SB_MBINIT_REPAIRVAL_INIT_RESP:       '{SB_OPCODE_NO_DATA, 8'hAA, 8'h09, 1'b0},
    SB_MBINIT_REPAIRVAL_RESULT_REQ:      '{SB_OPCODE_NO_DATA, 8'hA5, 8'h0A, 1'b0},
    SB_MBINIT_REPAIRVAL_RESULT_RESP:     '{SB_OPCODE_NO_DATA, 8'hAA, 8'h0A, 1'b0},
    SB_MBINIT_REPAIRVAL_APPLY_REPAIR_REQ: '{SB_OPCODE_DATA, 8'hA5, 8'h0B, 1'b1},
    SB_MBINIT_REPAIRVAL_APPLY_REPAIR_RESP: '{SB_OPCODE_NO_DATA, 8'hAA, 8'h0B, 1'b0},
    SB_MBINIT_REPAIRVAL_DONE_REQ:        '{SB_OPCODE_NO_DATA, 8'hA5, 8'h0C, 1'b0},
    SB_MBINIT_REPAIRVAL_DONE_RESP:       '{SB_OPCODE_NO_DATA, 8'hAA, 8'h0C, 1'b0},

    /* =========================================================
     * MBINIT – REVERSALMB
     * ========================================================= */
    SB_MBINIT_REVERSALMB_INIT_REQ:       '{SB_OPCODE_NO_DATA, 8'hA5, 8'h0D, 1'b0},
    SB_MBINIT_REVERSALMB_INIT_RESP:      '{SB_OPCODE_NO_DATA, 8'hAA, 8'h0D, 1'b0},
    SB_MBINIT_REVERSALMB_CLEAR_ERROR_REQ: '{SB_OPCODE_NO_DATA, 8'hA5, 8'h0E, 1'b0},
    SB_MBINIT_REVERSALMB_CLEAR_ERROR_RESP: '{SB_OPCODE_NO_DATA, 8'hAA, 8'h0E, 1'b0},
    SB_MBINIT_REVERSALMB_RESULT_REQ:     '{SB_OPCODE_NO_DATA, 8'hA5, 8'h0F, 1'b0},
    SB_MBINIT_REVERSALMB_RESULT_RESP:    '{SB_OPCODE_NO_DATA, 8'hAA, 8'h0F, 1'b0},
    SB_MBINIT_REVERSALMB_DONE_REQ:       '{SB_OPCODE_NO_DATA, 8'hA5, 8'h10, 1'b0},
    SB_MBINIT_REVERSALMB_DONE_RESP:      '{SB_OPCODE_NO_DATA, 8'hAA, 8'h10, 1'b0},

    /* =========================================================
     * MBINIT – REPAIRMB
     * ========================================================= */
    SB_MBINIT_REPAIRMB_START_REQ:        '{SB_OPCODE_NO_DATA, 8'hA5, 8'h11, 1'b0},
    SB_MBINIT_REPAIRMB_START_RESP:       '{SB_OPCODE_NO_DATA, 8'hAA, 8'h11, 1'b0},
    SB_MBINIT_REPAIRMB_APPLY_REPAIR_REQ: '{SB_OPCODE_DATA, 8'hA5, 8'h12, 1'b1},
    SB_MBINIT_REPAIRMB_APPLY_REPAIR_RESP: '{SB_OPCODE_NO_DATA, 8'hAA, 8'h12, 1'b0},
    SB_MBINIT_REPAIRMB_END_REQ:          '{SB_OPCODE_NO_DATA, 8'hA5, 8'h13, 1'b0},
    SB_MBINIT_REPAIRMB_END_RESP:         '{SB_OPCODE_NO_DATA, 8'hAA, 8'h13, 1'b0},
    SB_MBINIT_REPAIRMB_APPLY_DEGRADE_REQ: '{SB_OPCODE_NO_DATA, 8'hA5, 8'h14, 1'b0},
    SB_MBINIT_REPAIRMB_APPLY_DEGRADE_RESP: '{SB_OPCODE_NO_DATA, 8'hAA, 8'h14, 1'b0},

    /* =========================================================
     * MBTRAIN – VREF / CENTER / SPEED / REPAIR
     * ========================================================= */
    SB_MBTRAIN_VALVREF_START_REQ:        '{SB_OPCODE_NO_DATA, 8'hB5, 8'h00, 1'b0},
    SB_MBTRAIN_VALVREF_START_RESP:       '{SB_OPCODE_NO_DATA, 8'hBA, 8'h00, 1'b0},
    SB_MBTRAIN_VALVREF_END_REQ:          '{SB_OPCODE_NO_DATA, 8'hB5, 8'h01, 1'b0},
    SB_MBTRAIN_VALVREF_END_RESP:         '{SB_OPCODE_NO_DATA, 8'hBA, 8'h01, 1'b0},

    SB_MBTRAIN_DATAVREF_START_REQ:       '{SB_OPCODE_NO_DATA, 8'hB5, 8'h02, 1'b0},
    SB_MBTRAIN_DATAVREF_START_RESP:      '{SB_OPCODE_NO_DATA, 8'hBA, 8'h02, 1'b0},
    SB_MBTRAIN_DATAVREF_END_REQ:         '{SB_OPCODE_NO_DATA, 8'hB5, 8'h03, 1'b0},
    SB_MBTRAIN_DATAVREF_END_RESP:        '{SB_OPCODE_NO_DATA, 8'hBA, 8'h03, 1'b0},

    SB_MBTRAIN_SPEEDIDLE_DONE_REQ:       '{SB_OPCODE_NO_DATA, 8'hB5, 8'h04, 1'b0},
    SB_MBTRAIN_SPEEDIDLE_DONE_RESP:      '{SB_OPCODE_NO_DATA, 8'hBA, 8'h04, 1'b0},

    SB_MBTRAIN_TXSELFCAL_DONE_REQ:       '{SB_OPCODE_NO_DATA, 8'hB5, 8'h05, 1'b0},
    SB_MBTRAIN_TXSELFCAL_DONE_RESP:      '{SB_OPCODE_NO_DATA, 8'hBA, 8'h05, 1'b0},

    SB_MBTRAIN_RXCLKCAL_START_REQ:       '{SB_OPCODE_NO_DATA, 8'hB5, 8'h06, 1'b0},
    SB_MBTRAIN_RXCLKCAL_START_RESP:      '{SB_OPCODE_NO_DATA, 8'hBA, 8'h06, 1'b0},
    SB_MBTRAIN_RXCLKCAL_DONE_REQ:        '{SB_OPCODE_NO_DATA, 8'hB5, 8'h07, 1'b0},
    SB_MBTRAIN_RXCLKCAL_DONE_RESP:       '{SB_OPCODE_NO_DATA, 8'hBA, 8'h07, 1'b0},

    SB_MBTRAIN_VALTRAINCENTER_START_REQ: '{SB_OPCODE_NO_DATA, 8'hB5, 8'h08, 1'b0},
    SB_MBTRAIN_VALTRAINCENTER_START_RESP: '{SB_OPCODE_NO_DATA, 8'hBA, 8'h08, 1'b0},
    SB_MBTRAIN_VALTRAINCENTER_DONE_REQ:  '{SB_OPCODE_NO_DATA, 8'hB5, 8'h09, 1'b0},
    SB_MBTRAIN_VALTRAINCENTER_DONE_RESP: '{SB_OPCODE_NO_DATA, 8'hBA, 8'h09, 1'b0},

    SB_MBTRAIN_VALTRAINVREF_START_REQ:   '{SB_OPCODE_NO_DATA, 8'hB5, 8'h0A, 1'b0},
    SB_MBTRAIN_VALTRAINVREF_START_RESP:  '{SB_OPCODE_NO_DATA, 8'hBA, 8'h0A, 1'b0},
    SB_MBTRAIN_VALTRAINVREF_DONE_REQ:    '{SB_OPCODE_NO_DATA, 8'hB5, 8'h0B, 1'b0},
    SB_MBTRAIN_VALTRAINVREF_DONE_RESP:   '{SB_OPCODE_NO_DATA, 8'hBA, 8'h0B, 1'b0},

    SB_MBTRAIN_DATATRAINCENTER1_START_REQ: '{SB_OPCODE_NO_DATA, 8'hB5, 8'h0C, 1'b0},
    SB_MBTRAIN_DATATRAINCENTER1_START_RESP: '{SB_OPCODE_NO_DATA, 8'hBA, 8'h0C, 1'b0},
    SB_MBTRAIN_DATATRAINCENTER1_END_REQ: '{SB_OPCODE_NO_DATA, 8'hB5, 8'h0D, 1'b0},
    SB_MBTRAIN_DATATRAINCENTER1_END_RESP: '{SB_OPCODE_NO_DATA, 8'hBA, 8'h0D, 1'b0},

    SB_MBTRAIN_DATATRAINVREF_START_REQ:  '{SB_OPCODE_NO_DATA, 8'hB5, 8'h0E, 1'b0},
    SB_MBTRAIN_DATATRAINVREF_START_RESP: '{SB_OPCODE_NO_DATA, 8'hBA, 8'h0E, 1'b0},
    SB_MBTRAIN_DATATRAINVREF_END_REQ:    '{SB_OPCODE_NO_DATA, 8'hB5, 8'h10, 1'b0},
    SB_MBTRAIN_DATATRAINVREF_END_RESP:   '{SB_OPCODE_NO_DATA, 8'hBA, 8'h10, 1'b0},

    SB_MBTRAIN_RXDESKEW_START_REQ:       '{SB_OPCODE_NO_DATA, 8'hB5, 8'h11, 1'b0},
    SB_MBTRAIN_RXDESKEW_START_RESP:      '{SB_OPCODE_NO_DATA, 8'hBA, 8'h11, 1'b0},
    SB_MBTRAIN_RXDESKEW_END_REQ:         '{SB_OPCODE_NO_DATA, 8'hB5, 8'h12, 1'b0},
    SB_MBTRAIN_RXDESKEW_END_RESP:        '{SB_OPCODE_NO_DATA, 8'hBA, 8'h12, 1'b0},

    SB_MBTRAIN_DATATRAINCENTER2_START_REQ: '{SB_OPCODE_NO_DATA, 8'hB5, 8'h13, 1'b0},
    SB_MBTRAIN_DATATRAINCENTER2_START_RESP: '{SB_OPCODE_NO_DATA, 8'hBA, 8'h13, 1'b0},
    SB_MBTRAIN_DATATRAINCENTER2_END_REQ: '{SB_OPCODE_NO_DATA, 8'hB5, 8'h14, 1'b0},
    SB_MBTRAIN_DATATRAINCENTER2_END_RESP: '{SB_OPCODE_NO_DATA, 8'hBA, 8'h14, 1'b0},

    SB_MBTRAIN_LINKSPEED_START_REQ:      '{SB_OPCODE_NO_DATA, 8'hB5, 8'h15, 1'b0},
    SB_MBTRAIN_LINKSPEED_START_RESP:     '{SB_OPCODE_NO_DATA, 8'hBA, 8'h15, 1'b0},
    SB_MBTRAIN_LINKSPEED_ERROR_REQ:      '{SB_OPCODE_NO_DATA, 8'hB5, 8'h16, 1'b0},
    SB_MBTRAIN_LINKSPEED_ERROR_RESP:     '{SB_OPCODE_NO_DATA, 8'hBA, 8'h16, 1'b0},
    SB_MBTRAIN_LINKSPEED_EXIT_REPAIR_REQ: '{SB_OPCODE_NO_DATA, 8'hB5, 8'h17, 1'b0},
    SB_MBTRAIN_LINKSPEED_EXIT_REPAIR_RESP: '{SB_OPCODE_NO_DATA, 8'hBA, 8'h17, 1'b0},
    SB_MBTRAIN_LINKSPEED_EXIT_DEGRADE_REQ: '{SB_OPCODE_NO_DATA, 8'hB5, 8'h18, 1'b0},
    SB_MBTRAIN_LINKSPEED_EXIT_DEGRADE_RESP: '{SB_OPCODE_NO_DATA, 8'hBA, 8'h18, 1'b0},
    SB_MBTRAIN_LINKSPEED_DONE_REQ:       '{SB_OPCODE_NO_DATA, 8'hB5, 8'h19, 1'b0},
    SB_MBTRAIN_LINKSPEED_DONE_RESP:      '{SB_OPCODE_NO_DATA, 8'hBA, 8'h19, 1'b0},
    SB_MBTRAIN_LINKSPEED_EXIT_PHYRETRAIN_REQ: '{SB_OPCODE_NO_DATA, 8'hB5, 8'h1F, 1'b0},
    SB_MBTRAIN_LINKSPEED_EXIT_PHYRETRAIN_RESP: '{SB_OPCODE_NO_DATA, 8'hBA, 8'h1F, 1'b0},

    SB_MBTRAIN_REPAIR_INIT_REQ:          '{SB_OPCODE_NO_DATA, 8'hB5, 8'h1B, 1'b0},
    SB_MBTRAIN_REPAIR_INIT_RESP:         '{SB_OPCODE_NO_DATA, 8'hBA, 8'h1B, 1'b0},
    SB_MBTRAIN_REPAIR_APPLY_REPAIR_REQ:  '{SB_OPCODE_DATA, 8'hB5, 8'h1C, 1'b1},
    SB_MBTRAIN_REPAIR_APPLY_REPAIR_RESP: '{SB_OPCODE_NO_DATA, 8'hBA, 8'h1C, 1'b0},
    SB_MBTRAIN_REPAIR_END_REQ:           '{SB_OPCODE_NO_DATA, 8'hB5, 8'h1D, 1'b0},
    SB_MBTRAIN_REPAIR_END_RESP:          '{SB_OPCODE_NO_DATA, 8'hBA, 8'h1D, 1'b0},
    SB_MBTRAIN_REPAIR_APPLY_DEGRADE_REQ: '{SB_OPCODE_NO_DATA, 8'hB5, 8'h1E, 1'b0},
    SB_MBTRAIN_REPAIR_APPLY_DEGRADE_RESP: '{SB_OPCODE_NO_DATA, 8'hBA, 8'h1E, 1'b0},

    SB_MBTRAIN_RXDESKEW_EQ_PRESET_REQ:   '{SB_OPCODE_NO_DATA, 8'hB5, 8'h1F, 1'b0},
    SB_MBTRAIN_RXDESKEW_EQ_PRESET_RESP:  '{SB_OPCODE_NO_DATA, 8'hBA, 8'h1F, 1'b0},

    SB_MBTRAIN_RXDESKEW_EXIT_DTC1_REQ:   '{SB_OPCODE_NO_DATA, 8'hB5, 8'h20, 1'b0},
    SB_MBTRAIN_RXDESKEW_EXIT_DTC1_RESP:  '{SB_OPCODE_NO_DATA, 8'hBA, 8'h20, 1'b0},

    /* =========================================================
     * MBTRAIN – WITH DATA / PHY / RECAL
     * ========================================================= */
    SB_MBTRAIN_RXCLKCAL_TCKN_SHIFT_REQ:  '{SB_OPCODE_DATA, 8'hB5, 8'h21, 1'b0},
    SB_MBTRAIN_RXCLKCAL_TCKN_SHIFT_RESP: '{SB_OPCODE_DATA, 8'hBA, 8'h21, 1'b0},

    SB_PHYRETRAIN_START_REQ:             '{SB_OPCODE_DATA, 8'hC5, 8'h01, 1'b0},
    SB_PHYRETRAIN_START_RESP:            '{SB_OPCODE_DATA, 8'hCA, 8'h01, 1'b0},

    SB_TRAINERROR_ENTRY_REQ:             '{SB_OPCODE_NO_DATA, 8'hE5, 8'h00, 1'b0},
    SB_TRAINERROR_ENTRY_RESP:            '{SB_OPCODE_NO_DATA, 8'hEA, 8'h00, 1'b0},

    SB_RECAL_TRACK_PATTERN_INIT_REQ:     '{SB_OPCODE_NO_DATA, 8'hD5, 8'h00, 1'b0},
    SB_RECAL_TRACK_PATTERN_INIT_RESP:    '{SB_OPCODE_NO_DATA, 8'hDA, 8'h00, 1'b0},
    SB_RECAL_TRACK_PATTERN_DONE_REQ:     '{SB_OPCODE_NO_DATA, 8'hD5, 8'h01, 1'b0},
    SB_RECAL_TRACK_PATTERN_DONE_RESP:    '{SB_OPCODE_NO_DATA, 8'hDA, 8'h01, 1'b0},

    SB_RECAL_TRACK_TX_ADJUST_REQ:        '{SB_OPCODE_DATA, 8'hB5, 8'h22, 1'b0},
    SB_RECAL_TRACK_TX_ADJUST_RESP:       '{SB_OPCODE_DATA, 8'hBA, 8'h22, 1'b0},

    /* =========================================================
     * LINK MGMT – RDI REQUEST  (msgcode = 01h)
     * ========================================================= */
    SB_RDI_REQ_ACTIVE:                   '{SB_OPCODE_NO_DATA, 8'h01, 8'h01, 1'b0},
    SB_RDI_REQ_L1:                       '{SB_OPCODE_NO_DATA, 8'h01, 8'h04, 1'b0},
    SB_RDI_REQ_L2:                       '{SB_OPCODE_NO_DATA, 8'h01, 8'h08, 1'b0},
    SB_RDI_REQ_LINKRESET:                '{SB_OPCODE_NO_DATA, 8'h01, 8'h09, 1'b0},
    SB_RDI_REQ_LINKERROR:                '{SB_OPCODE_NO_DATA, 8'h01, 8'h0A, 1'b0},
    SB_RDI_REQ_RETRAIN:                  '{SB_OPCODE_NO_DATA, 8'h01, 8'h0B, 1'b0},
    SB_RDI_REQ_DISABLE:                  '{SB_OPCODE_NO_DATA, 8'h01, 8'h0C, 1'b0},

    /* =========================================================
     * LINK MGMT – RDI RESPONSE  (msgcode = 02h)
     * ========================================================= */
    SB_RDI_RSP_ACTIVE:                   '{SB_OPCODE_NO_DATA, 8'h02, 8'h01, 1'b0},
    SB_RDI_RSP_PMNAK:                    '{SB_OPCODE_NO_DATA, 8'h02, 8'h02, 1'b0},
    SB_RDI_RSP_L1:                       '{SB_OPCODE_NO_DATA, 8'h02, 8'h04, 1'b0},
    SB_RDI_RSP_L2:                       '{SB_OPCODE_NO_DATA, 8'h02, 8'h08, 1'b0},
    SB_RDI_RSP_LINKRESET:                '{SB_OPCODE_NO_DATA, 8'h02, 8'h09, 1'b0},
    SB_RDI_RSP_LINKERROR:                '{SB_OPCODE_NO_DATA, 8'h02, 8'h0A, 1'b0},
    SB_RDI_RSP_RETRAIN:                  '{SB_OPCODE_NO_DATA, 8'h02, 8'h0B, 1'b0},
    SB_RDI_RSP_DISABLE:                  '{SB_OPCODE_NO_DATA, 8'h02, 8'h0C, 1'b0}
  };
  
  endpackage: pckg